version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.16 # Choose an appropriate Docker image
    steps:
      - checkout # Check out your GitHub repository
      - run:
          name: Export AWS Environment Variables
          command: |
            export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            sudo apt-get update 
            sudo apt-get install -y awscli
            curl -O https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip            unzip terraform_0.12.28_linux_amd64.zip
            unzip terraform_0.12.28_linux_amd64.zip
            sudo mv terraform /usr/local/bin/
      - run:
          name: Upload to S3
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            terraform init
            terraform apply -auto-approve
      - persist_to_workspace:
          root: .
          paths:
            - terraform.tfstate
  deploy:
    docker:
      - image: circleci/golang:1.16 # Choose an appropriate Docker image
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          name: Export AWS Environment Variables
          command: |
            export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            sudo apt-get update 
            sudo apt-get install -y awscli
      - run:
          name: Deploy to S3
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            terraform init
            terraform apply -auto-approve
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
